### ISSUE TITLE
Conditions are evaluated too late for the defined tasks

### ISSUE THREAD

**Issue by MoonStorm** [nant/nant#108]
It seems an element gets fully constructed prior to evaluating the condition that allows the task to execute. This is causing problems for tasks which otherwise seem to be properly defined. 

For example, the next task fails with a "Property evaluation failed" error:
```
<arg value ="-exclude:${tests.exclude}" if="${property::exists('tests.exclude')}"/>
```

**Comment by rmboggs** [comment]
Confirmed that this is working as expected in master branch as of now.  Closing.
