### ISSUE TITLE
Bug in CopyTask recursively tries to copy the base directory instead of a single file

### ISSUE THREAD

**Issue by psantosl** [nant/nant#119]
I think there is a bug when a copy operation tries to copy to a path that doesn't exist.

It is very easy to reproduce with 0.92 and 0.93:

        <copy todir="${clientbinpath}/extensions/trac">
            <fileset>
                <include name="${libs}/xmlrpc.net/bin1_0/CookComputing.XmlRpc.dll" />
            </fileset>
        </copy>

Where "trac" doesn't exist and has to be created.

CopyTask tries to recursively copy the "base directory" into the destination directory, instead of copying just the right file.

In my case I get this error:

Cannot copy 'C:\Users\pablo\wkspaces\four\01nerva\' to 'C:\Users\pablo\wkspaces\four\01nerva\bin\client\extensions\trac'.
    The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

And "01nerva" is the basepath of my build file.

IMO the problem can be the calculation of IsEverythingIncluded of the CopyFileSet or maybe the calculation of the BaseDirectory of the FileSet, that doesn't take the content from the file list but from the project base directory.

The only workarounds I find right now:

* Set includeemptydirs = false if you're just copying files
* Create the directory before

**Comment by gamicklisafisher** [comment]
Long Path Tool is a best software to solve this issue. 5++ Rating. Long Path Tool is a best software
it is a free software. You can Try it

**Comment by rmboggs** [comment]
Thanks for the promotion of software that you have to pay for...

And thanks for reminding me to close this request as I pushed in the fix some time ago.
