### ISSUE TITLE
nant.sourceforge.net has been down for a while

### ISSUE THREAD

**Issue by novaterata** [nant/nant#153]
I have not been able to access the nant.sourceforge.net domain for over a week and http://www.isitdownrightnow.com/nant.sourceforge.net.html confirms it's not just me. I didn't know where else to put this.

**Comment by rmboggs** [comment]
It looks fine to me.  Just checked it seconds ago....

**Comment by novaterata** [comment]
It just came back up for me too, but that was the first time it was up in a while for me, maybe it's sporatic, but it's definitely going down at times.

**Comment by rmboggs** [comment]
I'm not doubting that.  I was just saying that it started working again when I checked.

Since it is sourceforge, we are pretty much at their mercy with uptime.  Not too much we can do at the moment.

**Comment by novaterata** [comment]
No doubt. It was just frustrating because every time I went to look up a task it was down. Now I know to just try again later.
