### ISSUE TITLE
Mail Task doesn't play nicely with TryCatch Task

### ISSUE THREAD

**Issue by andrewducker** [nant/nant#155]
If the Mail task fails to send a message, and gets a message back from the mail server, then it includes the exception in the exception it throws, but doesn't explicitly include the message from it in it's own text.

The TryCatch task, on the other hand, only picks up the text from the top-level exception, and not any of its children.

This means that if the Mail Task fails normally then you get:

    Error sending mail:
    Error enountered while sending mail message.
    Make sure that the following information is valid:
    Mailhost: mail.internal.xxx.com
    Mailport: 25
    Use SSL: False
    Using default credentials
    
    Mailbox unavailable. The server response was: test@test.com... No such user

However, if you wrap it with

    <catch property="unhandledFailure">
    	<echo message="${unhandledFailure}" />
    </catch>
then you get:

    [mail] Sending mail...
    [echo] Error sending mail:
    [echo] Error enountered while sending mail message.
    [echo] Make sure that the following information is valid:
    [echo] Mailhost: mail.internal.xxx.com
    [echo] Mailport: 25
    [echo] Use SSL: False
    [echo] Using default credentials
    [echo]

Which is missing the actual information which would make it possible to track down what went wrong!

Can I suggest that either 
1. TryCatch should concatenate the messages for the entire exception chain
2. Mail should append the exception message it catches to its own exception message.

**Comment by rmboggs** [comment]
Looks like TryCatch is neglecting any inner exceptions that may be attached to the Build exception that is being reported.  Since that is the case, there may be other scenarios that trycatch is dropping similar information.  It would be better to use your first suggestion to catch it all.  Should be fixed in pull request #160.  Can you please test when you can?

**Comment by rmboggs** [comment]
Fixed and committed in pull request #160.
