### ISSUE TITLE
.NET 1.1 is not detected on x64 windows

### ISSUE THREAD

**Issue by jonnyzzz** [nant/nant#56]
I see the error: 

    NAnt 0.92 (Build 0.92.4543.0; release; 09.06.2012)
    Copyright (C) 2001-2012 Gerry Shaw
    http://nant.sourceforge.net

    Microsoft .NET Framework 1.1 (net-1.1) is not installed, or not correctly configured.

        Framework directory 'C:\Windows\Microsoft.NET\Framework64\v1.1.4322' does not exist.

I checked and noticed NAnt.exe executes under x64 environment and thus accesses x64 version of registry.

So if I added x86 execution flag to NAnt, it becomes able to read x86 version of registry and thus detect .NET 1.1.
I run it on Windows 7 x64, I have .NET 1.1, .NET 2.0, .NET 4.0+4.5, VS 2008, VS 2010 installed.

**Comment by rmboggs** [comment]
I'm closing this as the changes described in this post were committed to App.config some time ago.

**Comment by BlackLocust** [comment]
The NAnt.exe.config file that comes with the installer does NOT include katlimruiz's recommended change.
