### ISSUE TITLE
0.92-alpha1 Property name 'sys.env.ProgramFiles(x86)' is invalid.

### ISSUE THREAD

**Issue by mgraves247** [nant/nant#63]
I have looked at numerous articles and it appears there was a bug, but that in the version of nant I have it should no longer be an issue if someone has a solution for this it would be greatly appreciated if you could post the resolution :-) This is on a Windows Server 2008 R2 I will post a copy of my Console below:

X:\InsightBuild>nant /f:InsightWeb.build buildStage
NAnt 0.92 (Build 0.92.4543.0; release; 6/9/2012)
Copyright (C) 2001-2012 Gerry Shaw
http://nant.sourceforge.net

Buildfile: file:///X:/InsightBuild/InsightWeb.build
Target framework: Microsoft .NET Framework 4.0
Target(s) specified: buildStage

  [sysinfo] Setting system information properties under sys.*

BUILD FAILED

Property name 'sys.env.ProgramFiles(x86)' is invalid.

Total time: 0.1 seconds.

**Comment by sunblognuke** [comment]
This solution works for us and saved us lots of time :)

**Comment by sunblognuke** [comment]
This solution works for us and saved us lots of time :)
