### ISSUE TITLE
/*.* behaves like /**/*.*

### ISSUE THREAD

**Issue by Kaiserludi** [nant/nant#64]
Our scripts make a lot use of  /*.* and /**/*.*.
The first copies all top level files in the folder, but no subfolders, the second one additionally also includes subfolders
This has worked fine until we have upgraded to version 0.9.2, but after upgrading /*.* now also copies includes the subfolders, so that the only way to only copy all the top-level files in a folder withouth also copying the subfolders, is, to specify every used file-ending separately. This can be reprocuded, by for example switching back to an older nant version like 0.91-alpha2 - the same unchanged scripts work correctly again, but only until switching forward to 0.92 again. i have not tried with any version between 0.91-alpha2 and 0.92, so I can't tell the exact version, that has introduced that bug.

**Comment by awglyde** [comment]
A bit late to the party. @rmboggs will a new version of nant-0.92 be posted on sourcetree that has this fix?
