### ISSUE TITLE
Problems with task copy and fileset

### ISSUE THREAD

**Issue by ocomeau** [nant/nant#88]
Hi I have a use case where copy doesn't work properly. We upgraded from nant 0.86 to 0.92 and here is the case :

--bat file
nant -buildfile:copy_error.build -D:temp.dir="..\DestinationDirError" -logfile:copy_error.txt
pause
--bat file

copy_error.build:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<project name="nant.test" default="build" basedir=".">
  <!-- Temporary directory path -->
  <property name="temp.dir" value="" overwrite="false" />
  <!-- Build directory -->
  <property name="build.dir" value="${temp.dir}\temp" readonly="true" />

  <target name="build">
    <copy todir="${build.dir}\SourceDir\Setup" verbose="true">
     <fileset>
        <include name="..\SourceDir\Setup\copy1.txt"/>
        <include name="..\SourceDir\Setup\copy2.txt"/>
      </fileset>
    <copy>
  </target>
</project>
```

The fileset doesn't seem to work, when you look into DestinaitonDir, it equals the content of ExecutionDir

If I had flatten="true" to the copy task, it works fine. Also, if I specified a base dir like this, it also works. 

``` xml
<fileset basedir="..\SourceDir\Setup">
  <include name="copy1.txt"/>
  <include name="copy2.txt"/>
</fileset> 
```

But what if I wanted something like this?

``` xml
<fileset>
  <include name="..\SourceDir\Setup\copy1.txt"/>
  <include name="..\SourceDirOther\Setup\other.txt"/>
</fileset>
```

I would have to do 2 copy?

Thanks

Edit : I had to remove "<" from each instruction for the code to show correctly. I have a zip file with all test case if you want.

**Comment by mwerle** [comment]
Sorry to dig this old issue up, but there hasn't been a new release of nant in a very long time. This means that 0.92 is still the current release and I just got hit by this particular issue. Any plans to make a new release?
