### ISSUE TITLE
Nant is unable to locate Windows SDK v8.0a for net 4.0 on 64bit machine

### ISSUE THREAD

**Issue by gkello** [nant/nant#93]
I'm trying to build Nant on 64bit machine having only .Net 4.5 SDK installed (v8.0A, comes with Visual Studio 2012). Nant version is "NAnt 0.93 (Build 0.93.4841.0; nightly; 3.04.2013)"

Result is
"
BUILD FAILED

The SDK for the 'net-4.0' framework is not available or not configured."

Doing a little research indicates that problem is how the v8.0a SDK is registered in regsitry. For 64 bit, it has only "WinSDK-NetFx35Tools" subkeys.

In Wow6432Node it has both "WinSDK-NetFx40Tools" and "WinSDK-NetFx35Tools" subkeys.

So, when nant is run as 64bit program the <locatesdk> taks fails to find net 4.0 sdk location. Seems like it should check some "default" sub-folders as well in addition to the ones found from registry

**Comment by rmboggs** [comment]
Merged.  Thanks for contributing.
